package com.springboot.core.service.impl;
import org.springframework.stereotype.Component;
import com.alibaba.dubbo.config.annotation.Service;
import javax.annotation.Resource;
import com.springboot.dao.RoleMapper;
import com.springboot.api.service.IRoleService;
import com.springboot.base.entity.Role;
/**
 *com.springboot.core.service.impl.IRoleServices.java
 *2019-06-06 02:40:48
 * This was class generated by ant velocity
 */
@Service
@Component
public class RoleServiceImpl implements IRoleService{
	
}
