package com.springboot.api.service;
import com.springboot.base.entity.Role;
/**
 *com.springboot.api.service.IRoleServices.java
 *2019-06-06 02:40:48
 * This was class generated by ant velocity
 */
public interface IRoleService {

}
