package com.springboot.api.service;
import com.springboot.base.entity.User;
/**
 *com.springboot.api.service.IUserServices.java
 *2019-06-06 11:37:04
 * This was class generated by ant velocity
 */
public interface IUserService {
	
	/**
	 * 新增用户
	 * @param user
	 * @return
	 */
	String addUser(User user);
	
	/**
	 * 新增用户信息到缓存
	 * @param user
	 * @return
	 */
	String addRedisCache(User user);

}
